package animal

import (
	"github.com/ironarachne/world/pkg/resource"
	"github.com/ironarachne/world/pkg/size"
)

func getMammals() []Animal {
	animals := []Animal{
		Animal{
			Name:           "beaver",
			PluralName:     "beavers",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      true,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 6,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "beaver hide",
					Origin: "beaver",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "beaver teeth",
					Origin: "beaver",
					Type:   "teeth",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "beaver meat",
					Origin: "beaver",
					Type:   "meat",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("small"),
		},
		Animal{
			Name:           "deer",
			PluralName:     "deer",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 10,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "deer hide",
					Origin: "deer",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "deer teeth",
					Origin: "deer",
					Type:   "teeth",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "venison",
					Origin: "deer",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "deer antler",
					Origin: "deer",
					Type:   "bone",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("medium"),
		},
		Animal{
			Name:           "squirrel",
			PluralName:     "squirrels",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 10,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "squirrel hide",
					Origin: "squirrel",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "squirrel meat",
					Origin: "squirrel",
					Type:   "meat",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("tiny"),
		},
		Animal{
			Name:           "camel",
			PluralName:     "camels",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        true,
			IsPackAnimal:   true,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    6,
			MinTemperature: 5,
			MaxTemperature: 10,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "camel hide",
					Origin: "camel",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "camel teeth",
					Origin: "camel",
					Type:   "teeth",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "camel meat",
					Origin: "camel",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "camel milk",
					Origin: "camel",
					Type:   "milk",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("medium"),
		},
		Animal{
			Name:           "bison",
			PluralName:     "bison",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 6,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "bison hide",
					Origin: "bison",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "bison teeth",
					Origin: "bison",
					Type:   "teeth",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "bison",
					Origin: "bison",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "bison bone",
					Origin: "bison",
					Type:   "bone",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("medium"),
		},
		Animal{
			Name:           "cow",
			PluralName:     "cows",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 10,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "leather",
					Origin: "cow",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "cow teeth",
					Origin: "cow",
					Type:   "teeth",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "beef",
					Origin: "cow",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "beef loin",
					Origin: "cow",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "beef ribs",
					Origin: "cow",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "cow bone",
					Origin: "cow",
					Type:   "bone",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("medium"),
		},
		Animal{
			Name:           "elephant",
			PluralName:     "elephants",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        true,
			IsPackAnimal:   true,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 5,
			MaxTemperature: 10,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "elephant hide",
					Origin: "elephant",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "elephant milk",
					Origin: "elephant",
					Type:   "milk",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "elephant",
					Origin: "elephant",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "ivory",
					Origin: "elephant",
					Type:   "bone",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("large"),
		},
		Animal{
			Name:           "goat",
			PluralName:     "goats",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 10,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "goat hide",
					Origin: "goat",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "goat's milk",
					Origin: "goat",
					Type:   "milk",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "goat",
					Origin: "goat",
					Type:   "meat",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("medium"),
		},
		Animal{
			Name:           "sheep",
			PluralName:     "sheep",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 10,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "wool",
					Origin: "sheep",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "sheep's milk",
					Origin: "sheep",
					Type:   "milk",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "lamb",
					Origin: "sheep",
					Type:   "meat",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("medium"),
		},
		Animal{
			Name:           "alpaca",
			PluralName:     "alpacas",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   true,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 4,
			MaxTemperature: 7,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "alpaca wool",
					Origin: "alpaca",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "alpaca milk",
					Origin: "alpaca",
					Type:   "milk",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "alpaca",
					Origin: "alpaca",
					Type:   "meat",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("medium"),
		},
		Animal{
			Name:           "llama",
			PluralName:     "llamas",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   true,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 7,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "llama wool",
					Origin: "llama",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "llama",
					Origin: "llama",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "llama milk",
					Origin: "llama",
					Type:   "milk",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("medium"),
		},
		Animal{
			Name:           "hippopotamus",
			PluralName:     "hippopotamuses",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      true,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "hippopotamus hide",
					Origin: "hippopotamus",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "hippopotamus",
					Origin: "hippopotamus",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "hippopotamus milk",
					Origin: "hippopotamus",
					Type:   "milk",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("large"),
		},
		Animal{
			Name:           "antelope",
			PluralName:     "antelopes",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "antelope hide",
					Origin: "antelope",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "antelope",
					Origin: "antelope",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "antelope milk",
					Origin: "antelope",
					Type:   "milk",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("medium"),
		},
		Animal{
			Name:           "gazelle",
			PluralName:     "gazelles",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "gazelle hide",
					Origin: "gazelle",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "gazelle",
					Origin: "gazelle",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "gazelle milk",
					Origin: "gazelle",
					Type:   "milk",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("medium"),
		},
		Animal{
			Name:           "rabbit",
			PluralName:     "rabbits",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 10,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "rabbit hide",
					Origin: "rabbit",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "rabbit",
					Origin: "rabbit",
					Type:   "meat",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("tiny"),
		},
		Animal{
			Name:           "ermine",
			PluralName:     "ermines",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 6,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "ermine fur",
					Origin: "ermine",
					Type:   "fur",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "ermine",
					Origin: "ermine",
					Type:   "meat",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("small"),
		},
		Animal{
			Name:           "mink",
			PluralName:     "minks",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 6,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "mink fur",
					Origin: "mink",
					Type:   "fur",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "mink",
					Origin: "mink",
					Type:   "meat",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("small"),
		},
		Animal{
			Name:           "pig",
			PluralName:     "pigs",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 10,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "pig hide",
					Origin: "pig",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "pork",
					Origin: "pig",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "pork loin",
					Origin: "pig",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "pork intestine",
					Origin: "pig",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "pork ribs",
					Origin: "pig",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "bacon",
					Origin: "pig",
					Type:   "meat",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("medium"),
		},
		Animal{
			Name:           "raccoon",
			PluralName:     "raccoons",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   false,
			IsScavenger:    true,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 7,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "raccoon hide",
					Origin: "raccoon",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "raccoon",
					Origin: "raccoon",
					Type:   "meat",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("small"),
		},
		Animal{
			Name:           "reindeer",
			PluralName:     "reindeer",
			AnimalType:     "mammal",
			EatsAnimals:    false,
			EatsPlants:     true,
			IsAquatic:      false,
			IsMount:        false,
			IsPackAnimal:   true,
			IsScavenger:    false,
			MinHumidity:    0,
			MaxHumidity:    10,
			MinTemperature: 0,
			MaxTemperature: 4,
			Resources: []resource.Resource{
				resource.Resource{
					Name:   "reindeer hide",
					Origin: "reindeer",
					Type:   "hide",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "reindeer",
					Origin: "reindeer",
					Type:   "meat",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "reindeer milk",
					Origin: "reindeer",
					Type:   "milk",
					Commonality: 5,
				},
				resource.Resource{
					Name:   "reindeer bone",
					Origin: "reindeer",
					Type:   "bone",
					Commonality: 5,
				},
			},
			Size: size.GetCategoryByName("medium"),
		},
	}

	return animals
}
