# Golang CircleCI 2.0 configuration file
#
# World API Project
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  test:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - run:
          name: Fetch dependencies
          command: go get -v -t -d ./...
      - run:
          name: Run tests
          command: |
            go test -short -coverprofile c.out ./...
      - sonarcloud/scan
  build:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: |
          VERSION_TAG=`cat ./VERSION`
          GIT_TAG=`git log -1 --pretty=%h`
          GOOS=linux GOARCH=amd64 go build -ldflags="-X 'github.com/ironarachne/world/cmd.Version=${VERSION_TAG}'" -o dist/world-linux-amd64-$VERSION_TAG
          GOOS=windows GOARCH=amd64 go build -ldflags="-X 'github.com/ironarachne/world/cmd.Version=${VERSION_TAG}'" -o dist/world-windows-amd64-$VERSION_TAG.exe
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X 'github.com/ironarachne/world/cmd.Version=${VERSION_TAG}'" -o dist/world-macos-amd64-$VERSION_TAG
          GOOS=darwin GOARCH=arm64 go build -ldflags="-X 'github.com/ironarachne/world/cmd.Version=${VERSION_TAG}'" -o dist/world-macos-arm64-$VERSION_TAG
workflows:
  version: 2
  test-build-publish:
    jobs:
      - test:
          context: SonarCloud
      - build:
          filters:
            branches:
              only: release
