# Golang CircleCI 2.0 configuration file
#
# World API Project
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  test:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - run:
          name: Fetch dependencies
          command: go get -v -t -d ./...
      - run:
          name: Run tests
          command: |
            go test -short -coverprofile c.out ./...
      - sonarcloud/scan
  build:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -v -t -d ./...
      - run: |
          cd cmd/worldapi
          cp -r ../../images .
          cp -r ../../data .
          VERSION_TAG=`cat ../../VERSION`
          GIT_TAG=`git log -1 --pretty=%h`
          docker build -t ironarachne/worldapi:$VERSION_TAG -t ironarachne/worldapi:$GIT_TAG -t ironarachne/worldapi:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ironarachne/worldapi:$VERSION_TAG
          docker push ironarachne/worldapi:$GIT_TAG
          docker push ironarachne/worldapi:latest

workflows:
  version: 2
  test-build-publish:
    jobs:
      - test:
          context: SonarCloud
      - build:
          filters:
            branches:
              only: release
