package charge

func getAnimalCharges() []Raster {
	charges := []Raster{
		{
			Identifier: "allocamelus",
			Name:       "allocamelus",
			Noun:       "allocamelus",
			NounPlural: "allocameluses",
			Descriptor: "",
			SingleOnly: false,
			Tags: []string{
				"allocamelus",
				"animal",
				"desert",
				"standing",
			},
		},
		{
			Identifier: "alphyn-salient",
			Name:       "alphyn salient",
			Noun:       "alphyn",
			NounPlural: "alphyns",
			Descriptor: "salient",
			SingleOnly: false,
			Tags: []string{
				"alphyn",
				"monster",
				"aggressive",
			},
		},
		{
			Identifier: "antelope-passant",
			Name:       "antelope passant",
			Noun:       "antelope",
			NounPlural: "antelopes",
			Descriptor: "passant",
			SingleOnly: false,
			Tags: []string{
				"animal",
				"antelope",
				"hunting",
				"passive",
			},
		},
		{
			Identifier: "antelope-rampant",
			Name:       "antelope rampant",
			Noun:       "antelope",
			NounPlural: "antelopes",
			Descriptor: "rampant",
			SingleOnly: false,
			Tags: []string{
				"animal",
				"antelope",
				"hunting",
				"aggressive",
			},
		},
		{
			Identifier: "antelope-statant",
			Name:       "antelope statant",
			Noun:       "antelope",
			NounPlural: "antelopes",
			Descriptor: "statant",
			SingleOnly: false,
			Tags: []string{
				"animal",
				"antelope",
				"hunting",
				"standing",
			},
		},
		{
			Identifier: "ape",
			Name:       "ape",
			Noun:       "ape",
			NounPlural: "apes",
			Descriptor: "",
			SingleOnly: false,
			Tags: []string{
				"ape",
				"animal",
				"passive",
			},
		},
		{
			Identifier: "ape-gorged-and-chained",
			Name:       "ape gorged and chained",
			Noun:       "ape",
			NounPlural: "apes",
			Descriptor: "gorged and chained",
			SingleOnly: false,
			Tags: []string{
				"ape",
				"animal",
			},
		},
		{
			Identifier: "bat-volant",
			Name:       "bat volant",
			Noun:       "bat",
			NounPlural: "bats",
			Descriptor: "volant",
			SingleOnly: false,
			Tags: []string{
				"bat",
				"animal",
				"passive",
				"hunting",
			},
		},
		{
			Identifier: "bear-passant",
			Name:       "bear passant",
			Noun:       "bear",
			NounPlural: "bears",
			Descriptor: "passant",
			SingleOnly: false,
			Tags: []string{
				"bear",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "bear-rampant",
			Name:       "bear rampant",
			Noun:       "bear",
			NounPlural: "bears",
			Descriptor: "rampant",
			SingleOnly: false,
			Tags: []string{
				"bear",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "bear-sejant-erect",
			Name:       "bear sejant erect",
			Noun:       "bear",
			NounPlural: "bears",
			Descriptor: "sejant erect",
			SingleOnly: false,
			Tags: []string{
				"bear",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "bear-statant",
			Name:       "bear statant",
			Noun:       "bear",
			NounPlural: "bears",
			Descriptor: "statant",
			SingleOnly: false,
			Tags: []string{
				"bear",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "bears-head-couped",
			Name:       "bear's head couped",
			Noun:       "bear's head",
			NounPlural: "bear's heads",
			Descriptor: "couped",
			SingleOnly: false,
			Tags: []string{
				"bear",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "boar-passant",
			Name:       "boar passant",
			Noun:       "boar",
			NounPlural: "boars",
			Descriptor: "passant",
			SingleOnly: false,
			Tags: []string{
				"boar",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "boar-rampant",
			Name:       "boar rampant",
			Noun:       "boar",
			NounPlural: "boars",
			Descriptor: "rampant",
			SingleOnly: false,
			Tags: []string{
				"boar",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "boar-statant",
			Name:       "boar statant",
			Noun:       "boar",
			NounPlural: "boars",
			Descriptor: "statant",
			SingleOnly: false,
			Tags: []string{
				"boar",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "boars-head-erased",
			Name:       "boar's head erased",
			Noun:       "boar's head",
			NounPlural: "boar's heads",
			Descriptor: "erased",
			SingleOnly: false,
			Tags: []string{
				"boar",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "bull-passant",
			Name:       "bull passant",
			Noun:       "bull",
			NounPlural: "bulls",
			Descriptor: "passant",
			SingleOnly: false,
			Tags: []string{
				"bull",
				"animal",
				"aggressive",
				"strength",
			},
		},
		{
			Identifier: "bull-rampant",
			Name:       "bull rampant",
			Noun:       "bull",
			NounPlural: "bulls",
			Descriptor: "rampant",
			SingleOnly: false,
			Tags: []string{
				"bull",
				"animal",
				"aggressive",
				"strength",
			},
		},
		{
			Identifier: "escallop",
			Name:       "escallop",
			Noun:       "escallop",
			NounPlural: "escallops",
			Descriptor: "",
			SingleOnly: false,
			Tags: []string{
				"escallop",
				"animal",
				"water",
				"navy",
				"sailor",
			},
		},
		{
			Identifier: "fox-passant",
			Name:       "fox passant",
			Noun:       "fox",
			NounPlural: "foxes",
			Descriptor: "passant",
			SingleOnly: false,
			Tags: []string{
				"fox",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "fox-sejant",
			Name:       "fox sejant",
			Noun:       "fox",
			NounPlural: "foxes",
			Descriptor: "sejant",
			SingleOnly: false,
			Tags: []string{
				"fox",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "goat-salient",
			Name:       "goat salient",
			Noun:       "goat",
			NounPlural: "goats",
			Descriptor: "salient",
			SingleOnly: false,
			Tags: []string{
				"goat",
				"animal",
				"hunting",
			},
		},
		{
			Identifier: "hare",
			Name:       "hare",
			Noun:       "hare",
			NounPlural: "hares",
			Descriptor: "",
			SingleOnly: false,
			Tags: []string{
				"hare",
				"animal",
				"passive",
				"hunting",
			},
		},
		{
			Identifier: "hare-salient",
			Name:       "hare salient",
			Noun:       "hare",
			NounPlural: "hares",
			Descriptor: "salient",
			SingleOnly: false,
			Tags: []string{
				"hare",
				"animal",
				"passive",
				"hunting",
			},
		},
		{
			Identifier: "hind-statant",
			Name:       "hind statant",
			Noun:       "hind",
			NounPlural: "hinds",
			Descriptor: "statant",
			SingleOnly: false,
			Tags: []string{
				"hind",
				"animal",
				"passive",
				"hunting",
			},
		},
		{
			Identifier: "horse-passant",
			Name:       "horse passant",
			Noun:       "horse",
			NounPlural: "horses",
			Descriptor: "passant",
			SingleOnly: false,
			Tags: []string{
				"horse",
				"animal",
				"passive",
			},
		},
		{
			Identifier: "horse-rampant",
			Name:       "horse rampant",
			Noun:       "horse",
			NounPlural: "horses",
			Descriptor: "rampant",
			SingleOnly: false,
			Tags: []string{
				"horse",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "leopards-head-erased",
			Name:       "leopard's head erased",
			Noun:       "leopard's head",
			NounPlural: "leopard's heads",
			Descriptor: "erased",
			SingleOnly: false,
			Tags: []string{
				"leopard",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "otter",
			Name:       "otter",
			Noun:       "otter",
			NounPlural: "otters",
			Descriptor: "",
			SingleOnly: false,
			Tags: []string{
				"otter",
				"animal",
				"passive",
			},
		},
		{
			Identifier: "pegasus-passant",
			Name:       "pegasus passant",
			Noun:       "pegasus",
			NounPlural: "pegasi",
			Descriptor: "passant",
			SingleOnly: false,
			Tags: []string{
				"pegasus",
				"monster",
				"passive",
			},
		},
		{
			Identifier: "pegasus-rampant",
			Name:       "pegasus rampant",
			Noun:       "pegasus",
			NounPlural: "pegasi",
			Descriptor: "rampant",
			SingleOnly: false,
			Tags: []string{
				"pegasus",
				"monster",
				"aggressive",
			},
		},
		{
			Identifier: "ram-rampant",
			Name:       "ram rampant",
			Noun:       "ram",
			NounPlural: "rams",
			Descriptor: "rampant",
			SingleOnly: false,
			Tags: []string{
				"ram",
				"animal",
				"hunting",
			},
		},
		{
			Identifier: "ram-statant",
			Name:       "ram statant",
			Noun:       "ram",
			NounPlural: "rams",
			Descriptor: "statant",
			SingleOnly: false,
			Tags: []string{
				"ram",
				"animal",
				"hunting",
			},
		},
		{
			Identifier: "rams-head-caboshed",
			Name:       "ram's head caboshed",
			Noun:       "ram's head",
			NounPlural: "ram's heads",
			Descriptor: "caboshed",
			SingleOnly: false,
			Tags: []string{
				"ram",
				"animal",
				"hunting",
			},
		},
		{
			Identifier: "sea-horse",
			Name:       "sea horse",
			Noun:       "sea horse",
			NounPlural: "sea horses",
			Descriptor: "",
			SingleOnly: false,
			Tags: []string{
				"sea horse",
				"animal",
				"water",
				"navy",
				"sailor",
			},
		},
		{
			Identifier: "sheep-passant",
			Name:       "sheep passant",
			Noun:       "sheep",
			NounPlural: "sheeps",
			Descriptor: "passant",
			SingleOnly: false,
			Tags: []string{
				"sheep",
				"animal",
				"passive",
			},
		},
		{
			Identifier: "squirrel",
			Name:       "squirrel",
			Noun:       "squirrel",
			NounPlural: "squirrels",
			Descriptor: "",
			SingleOnly: false,
			Tags: []string{
				"squirrel",
				"animal",
				"passive",
			},
		},
		{
			Identifier: "stag-at-gaze",
			Name:       "stag at gaze",
			Noun:       "stag",
			NounPlural: "stags",
			Descriptor: "at gaze",
			SingleOnly: false,
			Tags: []string{
				"stag",
				"animal",
				"hunting",
			},
		},
		{
			Identifier: "stag-lodged",
			Name:       "stag lodged",
			Noun:       "stag",
			NounPlural: "stags",
			Descriptor: "lodged",
			SingleOnly: false,
			Tags: []string{
				"stag",
				"animal",
				"hunting",
			},
		},
		{
			Identifier: "stag-springing",
			Name:       "stag springing",
			Noun:       "stag",
			NounPlural: "stags",
			Descriptor: "springing",
			SingleOnly: false,
			Tags: []string{
				"stag",
				"animal",
				"hunting",
			},
		},
		{
			Identifier: "stag-statant",
			Name:       "stag statant",
			Noun:       "stag",
			NounPlural: "stags",
			Descriptor: "statant",
			SingleOnly: false,
			Tags: []string{
				"stag",
				"animal",
				"hunting",
			},
		},
		{
			Identifier: "stag-trippant",
			Name:       "stag trippant",
			Noun:       "stag",
			NounPlural: "stags",
			Descriptor: "trippant",
			SingleOnly: false,
			Tags: []string{
				"stag",
				"animal",
				"hunting",
			},
		},
		{
			Identifier: "stags-head-couped",
			Name:       "stag's head couped'",
			Noun:       "stag's head",
			NounPlural: "stag's heads",
			Descriptor: "couped",
			SingleOnly: false,
			Tags: []string{
				"stag",
				"animal",
				"hunting",
			},
		},
		{
			Identifier: "talbot-passant",
			Name:       "talbot passant",
			Noun:       "talbot",
			NounPlural: "talbots",
			Descriptor: "passant",
			SingleOnly: false,
			Tags: []string{
				"talbot",
				"animal",
				"passive",
				"hunting",
				"dog",
			},
		},
		{
			Identifier: "talbot-rampant",
			Name:       "talbot rampant",
			Noun:       "talbot",
			NounPlural: "talbots",
			Descriptor: "rampant",
			SingleOnly: false,
			Tags: []string{
				"talbot",
				"animal",
				"aggressive",
				"hunting",
				"dog",
			},
		},
		{
			Identifier: "talbot-sejant",
			Name:       "talbot sejant",
			Noun:       "talbot",
			NounPlural: "talbots",
			Descriptor: "sejant",
			SingleOnly: false,
			Tags: []string{
				"talbot",
				"animal",
				"passive",
				"hunting",
				"dog",
			},
		},
		{
			Identifier: "talbot-statant",
			Name:       "talbot statant",
			Noun:       "talbot",
			NounPlural: "talbots",
			Descriptor: "statant",
			SingleOnly: false,
			Tags: []string{
				"talbot",
				"animal",
				"passive",
				"hunting",
				"dog",
			},
		},
		{
			Identifier: "tiger-passant",
			Name:       "tiger passant",
			Noun:       "tiger",
			NounPlural: "tigers",
			Descriptor: "passant",
			SingleOnly: false,
			Tags: []string{
				"tiger",
				"animal",
				"cat",
				"aggressive",
			},
		},
		{
			Identifier: "tiger-rampant",
			Name:       "tiger rampant",
			Noun:       "tiger",
			NounPlural: "tigers",
			Descriptor: "rampant",
			SingleOnly: false,
			Tags: []string{
				"tiger",
				"animal",
				"cat",
				"aggressive",
			},
		},
		{
			Identifier: "wolf-courant",
			Name:       "wolf courant",
			Noun:       "wolf",
			NounPlural: "wolfs",
			Descriptor: "courant",
			SingleOnly: false,
			Tags: []string{
				"wolf",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "wolf-passant",
			Name:       "wolf passant",
			Noun:       "wolf",
			NounPlural: "wolfs",
			Descriptor: "passant",
			SingleOnly: false,
			Tags: []string{
				"wolf",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "wolf-rampant",
			Name:       "wolf rampant",
			Noun:       "wolf",
			NounPlural: "wolfs",
			Descriptor: "rampant",
			SingleOnly: false,
			Tags: []string{
				"wolf",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "wolf-salient",
			Name:       "wolf salient",
			Noun:       "wolf",
			NounPlural: "wolfs",
			Descriptor: "salient",
			SingleOnly: false,
			Tags: []string{
				"wolf",
				"animal",
				"aggressive",
			},
		},
		{
			Identifier: "wolf-statant",
			Name:       "wolf statant",
			Noun:       "wolf",
			NounPlural: "wolfs",
			Descriptor: "statant",
			SingleOnly: false,
			Tags: []string{
				"wolf",
				"animal",
				"aggressive",
			},
		},
	}

	return charges
}
