package race

func getAllRaces() []Race {
	races := []Race{
		Race{
			Name:      "human",
			Adjective: "human",
			AgeCategories: []AgeCategory{
				AgeCategory{
					Name:        "adult",
					MinAge:      26,
					MaxAge:      69,
					Commonality: 12,
				},
				AgeCategory{
					Name:        "elderly",
					MinAge:      70,
					MaxAge:      110,
					Commonality: 1,
				},
				AgeCategory{
					Name:        "young adult",
					MinAge:      20,
					MaxAge:      25,
					Commonality: 2,
				},
				AgeCategory{
					Name:        "teenager",
					MinAge:      13,
					MaxAge:      19,
					Commonality: 1,
				},
				AgeCategory{
					Name:        "child",
					MinAge:      2,
					MaxAge:      12,
					Commonality: 1,
				},
				AgeCategory{
					Name:        "infant",
					MinAge:      0,
					MaxAge:      1,
					Commonality: 1,
				},
			},
			Appearance: Appearance{
				MaxFemaleHeight: 72,
				MinFemaleHeight: 48,
				MaxMaleHeight:   80,
				MinMaleHeight:   55,
				MaxFemaleWeight: 150,
				MinFemaleWeight: 90,
				MaxMaleWeight:   250,
				MinMaleWeight:   150,
				FaceShapes: []string{
					"broad",
					"chiseled",
					"oval",
					"round",
					"square",
				},
				EarShapes: []string{
					"rounded",
					"slightly pointed",
				},
				EyeShapes: []string{
					"almond",
					"narrow",
					"oval",
					"round",
					"slanted",
				},
				NoseShapes: []string{
					"acquiline",
					"long",
					"narrow",
					"pointed",
					"thin",
					"wide",
				},
				MouthShapes: []string{
					"full",
					"narrow",
					"thin",
					"wide",
				},
				FacialHairStyles: []string{
					"full beard",
					"short goatee",
					"long goatee",
					"handlebar mustache",
					"long beard",
					"short beard",
					"mutton chops",
					"clean shaven",
					"trim mustache",
					"narrow mustache",
				},
				HairColors: []string{
					"black",
					"auburn",
					"red",
					"grey",
					"brown",
					"dark brown",
					"light brown",
				},
				HairConsistencies: []string{
					"thick",
					"thin",
				},
				FemaleHairStyles: []string{
					"shoulder-length",
					"short-cropped",
					"bald",
					"bowl-cut",
					"ponytail",
					"topknot",
					"braided",
					"back-length",
					"mohawk",
				},
				MaleHairStyles: []string{
					"shoulder-length",
					"short-cropped",
					"bald",
					"bowl-cut",
					"ponytail",
					"topknot",
					"braided",
					"back-length",
					"mohawk",
				},
				SkinColors: []string{
					"light",
					"tan",
					"olive",
					"bronze",
					"brown",
					"dark",
				},
				EyeColors: []string{
					"amber",
					"blue",
					"brown",
					"gold",
					"green",
					"hazel",
					"grey",
				},
				UniqueTraits: []string{},
			},
			Commonality: 10,
		},
		Race{
			Name:      "dwarf",
			Adjective: "dwarven",
			AgeCategories: []AgeCategory{
				AgeCategory{
					Name:        "adult",
					MinAge:      76,
					MaxAge:      269,
					Commonality: 12,
				},
				AgeCategory{
					Name:        "elderly",
					MinAge:      270,
					MaxAge:      500,
					Commonality: 1,
				},
				AgeCategory{
					Name:        "young adult",
					MinAge:      40,
					MaxAge:      75,
					Commonality: 2,
				},
				AgeCategory{
					Name:        "teenager",
					MinAge:      23,
					MaxAge:      39,
					Commonality: 1,
				},
				AgeCategory{
					Name:        "child",
					MinAge:      2,
					MaxAge:      22,
					Commonality: 1,
				},
				AgeCategory{
					Name:        "infant",
					MinAge:      0,
					MaxAge:      1,
					Commonality: 1,
				},
			},
			Appearance: Appearance{
				MaxFemaleHeight: 62,
				MinFemaleHeight: 38,
				MaxMaleHeight:   62,
				MinMaleHeight:   38,
				MaxFemaleWeight: 300,
				MinFemaleWeight: 150,
				MaxMaleWeight:   400,
				MinMaleWeight:   200,
				FaceShapes: []string{
					"chiseled",
					"square",
					"rectangular",
				},
				EarShapes: []string{
					"slightly pointed",
					"rounded",
					"slightly tapered",
				},
				EyeShapes: []string{
					"broad",
					"oval",
					"narrow",
				},
				NoseShapes: []string{
					"wide",
					"large",
					"hooked",
					"strong",
				},
				MouthShapes: []string{
					"wide",
					"thin",
				},
				FacialHairStyles: []string{
					"braided beard",
					"bristly beard",
					"enormous beard",
					"long beard",
					"robust beard",
					"wide beard",
				},
				HairColors: []string{
					"auburn",
					"black",
					"dark brown",
					"dusty brown",
					"grey",
					"orange",
					"red",
					"white",
				},
				HairConsistencies: []string{
					"thick",
				},
				FemaleHairStyles: []string{
					"shoulder-length",
					"ponytail",
					"topknot",
					"braided",
					"back-length",
				},
				MaleHairStyles: []string{
					"shoulder-length",
					"short-cropped",
					"ponytail",
					"topknot",
					"braided",
					"back-length",
				},
				SkinColors: []string{
					"bronzed",
					"tan",
					"ruddy",
				},
				EyeColors: []string{
					"amber",
					"blue",
					"brown",
					"gold",
					"green",
					"hazel",
					"grey",
				},
				UniqueTraits: []string{},
			},
			Commonality: 2,
		},
		Race{
			Name:      "elf",
			Adjective: "elven",
			AgeCategories: []AgeCategory{
				AgeCategory{
					Name:        "adult",
					MinAge:      76,
					MaxAge:      269,
					Commonality: 12,
				},
				AgeCategory{
					Name:        "elderly",
					MinAge:      270,
					MaxAge:      500,
					Commonality: 1,
				},
				AgeCategory{
					Name:        "young adult",
					MinAge:      40,
					MaxAge:      75,
					Commonality: 2,
				},
				AgeCategory{
					Name:        "teenager",
					MinAge:      23,
					MaxAge:      39,
					Commonality: 1,
				},
				AgeCategory{
					Name:        "child",
					MinAge:      2,
					MaxAge:      22,
					Commonality: 1,
				},
				AgeCategory{
					Name:        "infant",
					MinAge:      0,
					MaxAge:      1,
					Commonality: 1,
				},
			},
			Appearance: Appearance{
				MaxFemaleHeight: 62,
				MinFemaleHeight: 38,
				MaxMaleHeight:   70,
				MinMaleHeight:   45,
				MaxFemaleWeight: 100,
				MinFemaleWeight: 50,
				MaxMaleWeight:   200,
				MinMaleWeight:   100,
				FaceShapes: []string{
					"chiseled",
					"oval",
					"triangular",
				},
				EarShapes: []string{
					"slightly pointed",
					"steeply pointed",
					"long and pointed",
				},
				EyeShapes: []string{
					"almond",
					"narrow",
					"slanted",
				},
				NoseShapes: []string{
					"long",
					"pointed",
					"thin",
					"slender",
				},
				MouthShapes: []string{
					"narrow",
					"thin",
				},
				FacialHairStyles: []string{
					"short goatee",
					"long goatee",
					"clean shaven",
				},
				HairColors: []string{
					"auburn",
					"grey",
					"white",
					"silver",
					"light blonde",
				},
				HairConsistencies: []string{
					"thick",
					"thin",
				},
				FemaleHairStyles: []string{
					"shoulder-length",
					"ponytail",
					"topknot",
					"braided",
					"back-length",
				},
				MaleHairStyles: []string{
					"shoulder-length",
					"short-cropped",
					"ponytail",
					"topknot",
					"braided",
					"back-length",
				},
				SkinColors: []string{
					"light",
					"tan",
					"pale",
				},
				EyeColors: []string{
					"amber",
					"blue",
					"brown",
					"gold",
					"green",
					"hazel",
					"grey",
					"purple",
					"silver",
				},
				UniqueTraits: []string{},
			},
			Commonality: 2,
		},
	}

	return races
}
