package fish

import "github.com/ironarachne/world/pkg/species"

func getLakeFish() []species.Species {
	fish := []species.Species{
		{
			Name:           "largemouth bass",
			PluralName:     "largemouth bass",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "channel catfish",
			PluralName:     "channel catfish",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "bluegill",
			PluralName:     "bluegills",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "coppernose bluegill",
			PluralName:     "coppernose bluegills",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "sunfish",
			PluralName:     "sunfish",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "gizzard shad",
			PluralName:     "gizzard shads",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "golden shiner",
			PluralName:     "golden shiners",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "fathead minnow",
			PluralName:     "fathead minnows",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "mosquitofish",
			PluralName:     "mosquitofish",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "striped bass",
			PluralName:     "striped bass",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "threadfin shad",
			PluralName:     "threadfin shads",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "tilapia",
			PluralName:     "tilapia",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "grass carp",
			PluralName:     "grass carp",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "koi",
			PluralName:     "koi",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "tiger muskie",
			PluralName:     "tiger muskies",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "muskellunge",
			PluralName:     "muskellunges",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "yellow perch",
			PluralName:     "yellow perches",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "black crappie",
			PluralName:     "black crappie",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "white sucker",
			PluralName:     "white suckers",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "rainbow trout",
			PluralName:     "rainbow trouts",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "golden rainbow trout",
			PluralName:     "golden rainbow trouts",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "brook trout",
			PluralName:     "brook trouts",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "brown trout",
			PluralName:     "brown trouts",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
		{
			Name:           "tiger trout",
			PluralName:     "tiger trout",
			MinTemperature: 2,
			MaxTemperature: 8,
			MinHumidity:    3,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in lakes",
			},
		},
	}

	return fish
}
