package fish

func getLakeFish() []Fish {
	fish := []Fish{
		{
			Name:             "largemouth bass",
			PluralName:       "largemouth bass",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "channel catfish",
			PluralName:       "channel catfish",
			IdealTemperature: 7,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "bluegill",
			PluralName:       "bluegills",
			IdealTemperature: 7,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "coppernose bluegill",
			PluralName:       "coppernose bluegills",
			IdealTemperature: 7,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "sunfish",
			PluralName:       "sunfish",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "gizzard shad",
			PluralName:       "gizzard shads",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "golden shiner",
			PluralName:       "golden shiners",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "fathead minnow",
			PluralName:       "fathead minnows",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "mosquitofish",
			PluralName:       "mosquitofish",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "striped bass",
			PluralName:       "striped bass",
			IdealTemperature: 7,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "threadfin shad",
			PluralName:       "threadfin shads",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "tilapia",
			PluralName:       "tilapia",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "grass carp",
			PluralName:       "grass carp",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "koi",
			PluralName:       "koi",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "tiger muskie",
			PluralName:       "tiger muskies",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "muskellunge",
			PluralName:       "muskellunges",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "yellow perch",
			PluralName:       "yellow perches",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "black crappie",
			PluralName:       "black crappie",
			IdealTemperature: 7,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "white sucker",
			PluralName:       "white suckers",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "rainbow trout",
			PluralName:       "rainbow trouts",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "golden rainbow trout",
			PluralName:       "golden rainbow trouts",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "brook trout",
			PluralName:       "brook trouts",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "brown trout",
			PluralName:       "brown trouts",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
		{
			Name:             "tiger trout",
			PluralName:       "tiger trout",
			IdealTemperature: 5,
			LivesInLakes:     true,
			LivesInOceans:    false,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"freshwater",
			},
		},
	}

	return fish
}
