package fish

import "github.com/ironarachne/world/pkg/species"

func getOceanFish() []species.Species {
	fish := []species.Species{
		{
			Name:           "bluefin tuna",
			PluralName:     "bluefin tuna",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "cod",
			PluralName:     "cod",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "goliath grouper",
			PluralName:     "goliath groupers",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "salmon",
			PluralName:     "salmon",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "trumpetfish",
			PluralName:     "trumpetfish",
			MinTemperature: 3,
			MaxTemperature: 10,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "wolffish",
			PluralName:     "wolffish",
			MinTemperature: 3,
			MaxTemperature: 10,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "butterflyfish",
			PluralName:     "butterflyfish",
			MinTemperature: 3,
			MaxTemperature: 10,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "beluga sturgeon",
			PluralName:     "beluga sturgeons",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "blue marlin",
			PluralName:     "blue marlins",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "blue tang",
			PluralName:     "blue tangs",
			MinTemperature: 3,
			MaxTemperature: 10,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "mackerel",
			PluralName:     "mackerels",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "clown triggerfish",
			PluralName:     "clown triggerfish",
			MinTemperature: 7,
			MaxTemperature: 10,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "fangtooth",
			PluralName:     "fangtooth",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "clownfish",
			PluralName:     "clownfish",
			MinTemperature: 7,
			MaxTemperature: 10,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "pufferfish",
			PluralName:     "pufferfish",
			MinTemperature: 3,
			MaxTemperature: 10,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "red snapper",
			PluralName:     "red snappers",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "ocean sunfish",
			PluralName:     "ocean sunfish",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "halibut",
			PluralName:     "halibut",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "sardine",
			PluralName:     "sardines",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "sailfish",
			PluralName:     "sailfish",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "moray eel",
			PluralName:     "moray eels",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"eel",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "swordfish",
			PluralName:     "swordfish",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "summer flounder",
			PluralName:     "summer flounders",
			MinTemperature: 3,
			MaxTemperature: 10,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "flying fish",
			PluralName:     "flying fish",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
		{
			Name:           "yellowfin tuna",
			PluralName:     "yellowfin tuna",
			MinTemperature: 3,
			MaxTemperature: 7,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"saltwater",
				"lives in oceans",
			},
		},
	}

	return fish
}
