package fish

func getOceanFish() []Fish {
	fish := []Fish{
		{
			Name:             "bluefin tuna",
			PluralName:       "bluefin tuna",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "cod",
			PluralName:       "cod",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "goliath grouper",
			PluralName:       "goliath groupers",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "salmon",
			PluralName:       "salmon",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "trumpetfish",
			PluralName:       "trumpetfish",
			IdealTemperature: 7,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "wolffish",
			PluralName:       "wolffish",
			IdealTemperature: 7,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "butterflyfish",
			PluralName:       "butterflyfish",
			IdealTemperature: 7,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "beluga sturgeon",
			PluralName:       "beluga sturgeons",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "blue marlin",
			PluralName:       "blue marlins",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "blue tang",
			PluralName:       "blue tangs",
			IdealTemperature: 7,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "mackerel",
			PluralName:       "mackerels",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "clown triggerfish",
			PluralName:       "clown triggerfish",
			IdealTemperature: 8,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "fangtooth",
			PluralName:       "fangtooth",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "clownfish",
			PluralName:       "clownfish",
			IdealTemperature: 8,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "pufferfish",
			PluralName:       "pufferfish",
			IdealTemperature: 7,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "red snapper",
			PluralName:       "red snappers",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "ocean sunfish",
			PluralName:       "ocean sunfish",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "halibut",
			PluralName:       "halibut",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "sardine",
			PluralName:       "sardines",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "sailfish",
			PluralName:       "sailfish",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "moray eel",
			PluralName:       "moray eels",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"eel",
				"saltwater",
			},
		},
		{
			Name:             "swordfish",
			PluralName:       "swordfish",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "summer flounder",
			PluralName:       "summer flounders",
			IdealTemperature: 7,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "flying fish",
			PluralName:       "flying fish",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
		{
			Name:             "yellowfin tuna",
			PluralName:       "yellowfin tuna",
			IdealTemperature: 5,
			LivesInLakes:     false,
			LivesInOceans:    true,
			LivesInRivers:    false,
			Tags: []string{
				"fish",
				"saltwater",
			},
		},
	}

	return fish
}
