package fish

import "github.com/ironarachne/world/pkg/species"

func getRiverFish() []species.Species {
	fish := []species.Species{
		{
			Name:           "smallmouth bass",
			PluralName:     "smallmouth bass",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "white bass",
			PluralName:     "white bass",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "silver carp",
			PluralName:     "silver carp",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "bighead carp",
			PluralName:     "bighead carp",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "black carp",
			PluralName:     "black carp",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "carp",
			PluralName:     "carp",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "flathead catfish",
			PluralName:     "flathead catfish",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "white crappie",
			PluralName:     "white crappies",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "eel",
			PluralName:     "eels",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"eel",
			},
		},
		{
			Name:           "long-nosed gar",
			PluralName:     "long-nosed gars",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "skipjack herring",
			PluralName:     "skipjack herrings",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "paddlefish",
			PluralName:     "paddlefish",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "northern pike",
			PluralName:     "northern pike",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "pumkinseed",
			PluralName:     "pumkinseeds",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "river redhorse",
			PluralName:     "river redhorse",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "sauger",
			PluralName:     "saugers",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "shovelnose sturgeon",
			PluralName:     "shovelnose sturgeons",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
		{
			Name:           "walleye",
			PluralName:     "walleye",
			MinTemperature: 3,
			MaxTemperature: 8,
			MinHumidity:    1,
			MaxHumidity:    10,
			Tags: []string{
				"fish",
				"freshwater",
				"lives in rivers",
			},
		},
	}

	return fish
}
