package climate

// AllGenerators returns all climate generators
func AllGenerators() []Generator {
	generators := []Generator{
		{
			NameRoot: "coniferous forest",
			NameVariants: []string{
				"dense",
				"sparse",
			},
			Adjective:       "forest",
			TemperatureMin:  0,
			TemperatureMax:  7,
			HumidityMin:     0,
			HumidityMax:     9,
			ElevationMin:    0,
			ElevationMax:    10,
			AnimalMin:       10,
			AnimalMax:       30,
			PlantMin:        10,
			PlantMax:        40,
			TreeMin:         1,
			TreeMax:         10,
			RiverPrevalence: 5,
			LakePrevalence:  4,
			SoilTags: []string{
				"clay",
				"soil",
			},
			AnimalTags: []string{
				"bird",
				"fish",
				"mammal",
				"reptile",
			},
			PlantTags: []string{
				"bush",
				"fiber",
				"grain",
				"herb",
				"melon",
				"root",
				"squash",
				"vegetable",
			},
			TreeTags: []string{
				"coniferous",
			},
		},
		{
			NameRoot: "deciduous forest",
			NameVariants: []string{
				"dense",
				"sparse",
			},
			Adjective:       "forest",
			TemperatureMin:  0,
			TemperatureMax:  7,
			HumidityMin:     0,
			HumidityMax:     9,
			ElevationMin:    0,
			ElevationMax:    10,
			AnimalMin:       10,
			AnimalMax:       30,
			PlantMin:        10,
			PlantMax:        40,
			TreeMin:         1,
			TreeMax:         10,
			RiverPrevalence: 5,
			LakePrevalence:  4,
			SoilTags: []string{
				"clay",
				"soil",
			},
			AnimalTags: []string{
				"bird",
				"fish",
				"mammal",
				"reptile",
			},
			PlantTags: []string{
				"bush",
				"fiber",
				"grain",
				"herb",
				"melon",
				"root",
				"squash",
				"vegetable",
			},
			TreeTags: []string{
				"deciduous",
			},
		},
		{
			NameRoot: "desert",
			NameVariants: []string{
				"sandy",
				"rocky",
			},
			Adjective:       "desert",
			TemperatureMin:  8,
			TemperatureMax:  10,
			HumidityMin:     0,
			HumidityMax:     2,
			ElevationMin:    0,
			ElevationMax:    3,
			AnimalMin:       3,
			AnimalMax:       10,
			PlantMin:        2,
			PlantMax:        10,
			TreeMin:         1,
			TreeMax:         2,
			RiverPrevalence: 1,
			LakePrevalence:  0,
			SoilTags: []string{
				"sand",
			},
			AnimalTags: []string{
				"bird",
				"mammal",
				"reptile",
			},
			PlantTags: []string{
				"cactus",
				"fiber",
				"grain",
				"root",
			},
			TreeTags: []string{
				"arid",
			},
		},
		{
			NameRoot: "grassland",
			NameVariants: []string{
				"flat",
				"hilly",
			},
			Adjective:       "grassland",
			TemperatureMin:  2,
			TemperatureMax:  7,
			HumidityMin:     1,
			HumidityMax:     9,
			ElevationMin:    1,
			ElevationMax:    6,
			AnimalMin:       5,
			AnimalMax:       20,
			PlantMin:        5,
			PlantMax:        20,
			TreeMin:         1,
			TreeMax:         5,
			RiverPrevalence: 7,
			LakePrevalence:  5,
			SoilTags: []string{
				"clay",
				"soil",
			},
			AnimalTags: []string{
				"bird",
				"fish",
				"mammal",
				"reptile",
			},
			PlantTags: []string{
				"bush",
				"fiber",
				"grain",
				"herb",
				"melon",
				"root",
				"squash",
				"vegetable",
			},
			TreeTags: []string{
				"coniferous",
				"deciduous",
			},
		},
		{
			NameRoot: "marshland",
			NameVariants: []string{
				"murky",
				"foggy",
			},
			Adjective:       "marshland",
			TemperatureMin:  2,
			TemperatureMax:  7,
			HumidityMin:     4,
			HumidityMax:     9,
			ElevationMin:    0,
			ElevationMax:    4,
			AnimalMin:       5,
			AnimalMax:       20,
			PlantMin:        5,
			PlantMax:        20,
			TreeMin:         1,
			TreeMax:         5,
			RiverPrevalence: 8,
			LakePrevalence:  8,
			SoilTags: []string{
				"clay",
				"soil",
			},
			AnimalTags: []string{
				"bird",
				"fish",
				"mammal",
				"reptile",
			},
			PlantTags: []string{
				"bush",
				"fiber",
				"grain",
				"herb",
				"melon",
				"root",
				"squash",
				"vegetable",
			},
			TreeTags: []string{
				"coniferous",
				"deciduous",
			},
		},
		{
			NameRoot: "mountain",
			NameVariants: []string{
				"treacherous",
				"barren",
			},
			Adjective:       "mountainous",
			TemperatureMin:  0,
			TemperatureMax:  5,
			HumidityMin:     2,
			HumidityMax:     5,
			ElevationMin:    7,
			ElevationMax:    10,
			AnimalMin:       5,
			AnimalMax:       10,
			PlantMin:        2,
			PlantMax:        10,
			TreeMin:         2,
			TreeMax:         10,
			RiverPrevalence: 3,
			LakePrevalence:  2,
			SoilTags: []string{
				"soil",
			},
			AnimalTags: []string{
				"bird",
				"fish",
				"mammal",
			},
			PlantTags: []string{
				"bush",
				"fiber",
				"grain",
				"herb",
				"melon",
				"root",
				"squash",
				"vegetable",
			},
			TreeTags: []string{
				"coniferous",
				"deciduous",
			},
		},
		{
			NameRoot: "rainforest",
			NameVariants: []string{
				"tropical",
				"hot",
			},
			Adjective:       "rainforest",
			TemperatureMin:  6,
			TemperatureMax:  10,
			HumidityMin:     7,
			HumidityMax:     10,
			ElevationMin:    0,
			ElevationMax:    6,
			AnimalMin:       8,
			AnimalMax:       30,
			PlantMin:        8,
			PlantMax:        30,
			TreeMin:         4,
			TreeMax:         25,
			RiverPrevalence: 7,
			LakePrevalence:  5,
			SoilTags: []string{
				"clay",
				"soil",
			},
			AnimalTags: []string{
				"bird",
				"fish",
				"mammal",
				"reptile",
			},
			PlantTags: []string{
				"bush",
				"fiber",
				"grain",
				"herb",
				"melon",
				"root",
				"squash",
				"vegetable",
			},
			TreeTags: []string{
				"coniferous",
				"deciduous",
			},
		},
		{
			NameRoot: "savanna",
			NameVariants: []string{
				"barren",
				"vast",
			},
			Adjective:       "savanna",
			TemperatureMin:  5,
			TemperatureMax:  8,
			HumidityMin:     1,
			HumidityMax:     3,
			ElevationMin:    1,
			ElevationMax:    6,
			AnimalMin:       5,
			AnimalMax:       20,
			PlantMin:        5,
			PlantMax:        20,
			TreeMin:         1,
			TreeMax:         5,
			RiverPrevalence: 4,
			LakePrevalence:  1,
			SoilTags: []string{
				"clay",
				"soil",
			},
			AnimalTags: []string{
				"bird",
				"mammal",
				"reptile",
			},
			PlantTags: []string{
				"bush",
				"fiber",
				"grain",
				"herb",
				"melon",
				"root",
				"squash",
				"vegetable",
			},
			TreeTags: []string{
				"arid",
			},
		},
		{
			NameRoot: "steppe",
			NameVariants: []string{
				"windy",
				"sprawling",
			},
			Adjective:       "steppe",
			TemperatureMin:  2,
			TemperatureMax:  5,
			HumidityMin:     1,
			HumidityMax:     3,
			ElevationMin:    4,
			ElevationMax:    7,
			AnimalMin:       5,
			AnimalMax:       20,
			PlantMin:        5,
			PlantMax:        20,
			TreeMin:         0,
			TreeMax:         0,
			RiverPrevalence: 4,
			LakePrevalence:  1,
			SoilTags: []string{
				"clay",
				"soil",
			},
			AnimalTags: []string{
				"bird",
				"mammal",
				"reptile",
			},
			PlantTags: []string{
				"bush",
				"fiber",
				"grain",
				"herb",
				"melon",
				"root",
				"squash",
				"vegetable",
			},
			TreeTags: []string{},
		},
		{
			NameRoot: "taiga",
			NameVariants: []string{
				"dense",
				"misty",
				"sparse",
			},
			Adjective:       "taiga",
			TemperatureMin:  1,
			TemperatureMax:  4,
			HumidityMin:     1,
			HumidityMax:     9,
			ElevationMin:    1,
			ElevationMax:    6,
			AnimalMin:       5,
			AnimalMax:       20,
			PlantMin:        5,
			PlantMax:        20,
			TreeMin:         1,
			TreeMax:         5,
			RiverPrevalence: 7,
			LakePrevalence:  5,
			SoilTags: []string{
				"clay",
				"soil",
			},
			AnimalTags: []string{
				"bird",
				"fish",
				"mammal",
				"reptile",
			},
			PlantTags: []string{
				"bush",
				"fiber",
				"grain",
				"herb",
				"melon",
				"root",
				"squash",
				"vegetable",
			},
			TreeTags: []string{
				"coniferous",
			},
		},
		{
			NameRoot: "tundra",
			NameVariants: []string{
				"cold",
				"flat",
			},
			Adjective:       "tundra",
			TemperatureMin:  0,
			TemperatureMax:  2,
			HumidityMin:     0,
			HumidityMax:     3,
			ElevationMin:    1,
			ElevationMax:    6,
			AnimalMin:       5,
			AnimalMax:       12,
			PlantMin:        2,
			PlantMax:        10,
			TreeMin:         1,
			TreeMax:         5,
			RiverPrevalence: 7,
			LakePrevalence:  5,
			SoilTags: []string{
				"clay",
				"soil",
			},
			AnimalTags: []string{
				"bird",
				"fish",
				"mammal",
			},
			PlantTags: []string{
				"bush",
				"fiber",
				"grain",
				"herb",
				"root",
				"squash",
				"vegetable",
			},
			TreeTags: []string{
				"coniferous",
				"deciduous",
			},
		},
	}

	return generators
}
