package climate

import "math/rand"

// Plant is a plant
type Plant struct {
	Name           string
	PluralName     string
	HasWood        bool
	IsFiber        bool
	IsFruit        bool
	IsGrain        bool
	IsHerb         bool
	IsMedicine     bool
	IsNut          bool
	IsRoot         bool
	IsSpice        bool
	IsToxic        bool
	IsTree         bool
	IsVegetable    bool
	MinHumidity    int
	MaxHumidity    int
	MinTemperature int
	MaxTemperature int
}

func (climate Climate) getFilteredPlants() []Plant {
	plants := getAllPlants()
	plants = filterPlantsForHumidity(climate.Humidity, plants)
	plants = filterPlantsForTemperature(climate.Temperature, plants)

	return plants
}

func getRandomPlants(amount int, from []Plant) []Plant {
	var plant Plant

	plants := []Plant{}

	if amount > len(from) {
		amount = len(from)
	}

	for i := 0; i < amount; i++ {
		plant = from[rand.Intn(len(from)-1)]
		if !isPlantInSlice(plant, plants) {
			plants = append(plants, plant)
		}
	}

	return plants
}

func isPlantInSlice(plant Plant, plants []Plant) bool {
	isIt := false
	for _, a := range plants {
		if a.Name == plant.Name {
			isIt = true
		}
	}

	return isIt
}

func filterPlantsForHumidity(humidity int, plants []Plant) []Plant {
	var filteredPlants []Plant

	for _, a := range plants {
		if a.MinHumidity <= humidity && a.MaxHumidity >= humidity {
			filteredPlants = append(filteredPlants, a)
		}
	}

	return filteredPlants
}

func filterPlantsForTemperature(temperature int, plants []Plant) []Plant {
	var filteredPlants []Plant

	for _, a := range plants {
		if a.MinTemperature <= temperature && a.MaxTemperature >= temperature {
			filteredPlants = append(filteredPlants, a)
		}
	}

	return filteredPlants
}

func getAllPlants() []Plant {
	var plants []Plant

	fibers := getFibers()
	plants = append(plants, fibers...)
	fruits := getFruits()
	plants = append(plants, fruits...)
	grains := getGrains()
	plants = append(plants, grains...)
	herbs := getHerbs()
	plants = append(plants, herbs...)
	trees := getTrees()
	plants = append(plants, trees...)
	vegetables := getVegetables()
	plants = append(plants, vegetables...)

	return plants
}

func getFibers() []Plant {
	fibers := []Plant{
		Plant{
			Name:           "cotton",
			PluralName:     "cotton",
			HasWood:        false,
			IsFiber:        true,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 9,
		},
		Plant{
			Name:           "flax",
			PluralName:     "flax",
			HasWood:        false,
			IsFiber:        true,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 9,
		},
		Plant{
			Name:           "hemp",
			PluralName:     "hemp",
			HasWood:        false,
			IsFiber:        true,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 9,
		},
		Plant{
			Name:           "coir",
			PluralName:     "coir",
			HasWood:        false,
			IsFiber:        true,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    6,
			MaxHumidity:    10,
			MinTemperature: 8,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "papyrus",
			PluralName:     "papyrus",
			HasWood:        false,
			IsFiber:        true,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 9,
		},
		Plant{
			Name:           "jute",
			PluralName:     "jute",
			HasWood:        false,
			IsFiber:        true,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 9,
		},
	}

	return fibers
}

func getFruits() []Plant {
	fruits := []Plant{
		Plant{
			Name:           "blackberry",
			PluralName:     "blackberries",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "blueberry",
			PluralName:     "blueberries",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "raspberry",
			PluralName:     "raspberries",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "strawberry",
			PluralName:     "strawberries",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "boysenberry",
			PluralName:     "boysenberries",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "gooseberry",
			PluralName:     "gooseberries",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "avocado",
			PluralName:     "avocados",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    6,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "banana",
			PluralName:     "bananas",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    5,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "coconut",
			PluralName:     "coconuts",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    5,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "mango",
			PluralName:     "mangoes",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    5,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "pineapple",
			PluralName:     "pineapples",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    5,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "lime",
			PluralName:     "limes",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    5,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "lemons",
			PluralName:     "lemons",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    5,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "dragonfruit",
			PluralName:     "dragonfruits",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    5,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "papaya",
			PluralName:     "papayas",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        true,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    5,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
		},
	}

	return fruits
}

func getGrains() []Plant {
	grains := []Plant{
		Plant{
			Name:           "rye",
			PluralName:     "ryes",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        true,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    7,
			MinTemperature: 3,
			MaxTemperature: 7,
		},
		Plant{
			Name:           "oat",
			PluralName:     "oats",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        true,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    7,
			MinTemperature: 3,
			MaxTemperature: 7,
		},
		Plant{
			Name:           "millet",
			PluralName:     "millets",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        true,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    7,
			MinTemperature: 3,
			MaxTemperature: 7,
		},
		Plant{
			Name:           "barley",
			PluralName:     "barleys",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        true,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    7,
			MinTemperature: 3,
			MaxTemperature: 7,
		},
		Plant{
			Name:           "wheat",
			PluralName:     "wheats",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        true,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    7,
			MinTemperature: 3,
			MaxTemperature: 7,
		},
		Plant{
			Name:           "rice",
			PluralName:     "rices",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        true,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    6,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
		},
	}

	return grains
}

func getHerbs() []Plant {
	herbs := []Plant{
		Plant{
			Name:           "parsley",
			PluralName:     "parsleys",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 3,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "brahmi",
			PluralName:     "brahmis",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     true,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 3,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "basil",
			PluralName:     "basils",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 3,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "cilantro",
			PluralName:     "cilantros",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 3,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "saffron",
			PluralName:     "saffrons",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    5,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "rosemary",
			PluralName:     "rosemarys",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 3,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "thyme",
			PluralName:     "thymes",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 3,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "black pepper",
			PluralName:     "black peppers",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 3,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "oregano",
			PluralName:     "oreganos",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 3,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "mint",
			PluralName:     "mints",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 3,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "lemongrass",
			PluralName:     "lemongrasses",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    5,
			MaxHumidity:    10,
			MinTemperature: 7,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "coriander",
			PluralName:     "corianders",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 3,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "clove",
			PluralName:     "cloves",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 3,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "sage",
			PluralName:     "sages",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 3,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "turmeric",
			PluralName:     "turmerics",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 7,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "vanilla",
			PluralName:     "vanillas",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 7,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "galangal",
			PluralName:     "galangals",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    5,
			MaxHumidity:    10,
			MinTemperature: 7,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "ginger",
			PluralName:     "gingers",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         true,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    false,
			MinHumidity:    5,
			MaxHumidity:    10,
			MinTemperature: 7,
			MaxTemperature: 10,
		},
	}

	return herbs
}

func getTrees() []Plant {
	trees := []Plant{
		Plant{
			Name:           "fir",
			PluralName:     "firs",
			HasWood:        true,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         true,
			IsVegetable:    false,
			MinHumidity:    2,
			MaxHumidity:    6,
			MinTemperature: 0,
			MaxTemperature: 5,
		},
		Plant{
			Name:           "aspen",
			PluralName:     "aspens",
			HasWood:        true,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         true,
			IsVegetable:    false,
			MinHumidity:    2,
			MaxHumidity:    6,
			MinTemperature: 0,
			MaxTemperature: 5,
		},
		Plant{
			Name:           "birch",
			PluralName:     "birches",
			HasWood:        true,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         true,
			IsVegetable:    false,
			MinHumidity:    2,
			MaxHumidity:    6,
			MinTemperature: 0,
			MaxTemperature: 5,
		},
		Plant{
			Name:           "oak",
			PluralName:     "oaks",
			HasWood:        true,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         true,
			IsVegetable:    false,
			MinHumidity:    2,
			MaxHumidity:    6,
			MinTemperature: 5,
			MaxTemperature: 7,
		},
		Plant{
			Name:           "elm",
			PluralName:     "elms",
			HasWood:        true,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         true,
			IsVegetable:    false,
			MinHumidity:    2,
			MaxHumidity:    6,
			MinTemperature: 5,
			MaxTemperature: 7,
		},
		Plant{
			Name:           "maple",
			PluralName:     "maples",
			HasWood:        true,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         true,
			IsVegetable:    false,
			MinHumidity:    2,
			MaxHumidity:    6,
			MinTemperature: 5,
			MaxTemperature: 7,
		},
		Plant{
			Name:           "palm",
			PluralName:     "palms",
			HasWood:        true,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         true,
			IsVegetable:    false,
			MinHumidity:    2,
			MaxHumidity:    10,
			MinTemperature: 6,
			MaxTemperature: 10,
		},
	}

	return trees
}

func getVegetables() []Plant {
	vegetables := []Plant{
		Plant{
			Name:           "potato",
			PluralName:     "potatoes",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         true,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "onion",
			PluralName:     "onions",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         true,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "beet",
			PluralName:     "beets",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         true,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "radish",
			PluralName:     "radishes",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         true,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "yam",
			PluralName:     "yams",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         true,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "carrot",
			PluralName:     "carrots",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         true,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "eggplant",
			PluralName:     "eggplants",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "kohlrabi",
			PluralName:     "kohlrabis",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "cabbage",
			PluralName:     "cabbages",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "lettuce",
			PluralName:     "lettuces",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "fiddlehead",
			PluralName:     "fiddleheads",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "broccoli",
			PluralName:     "broccolis",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "cauliflower",
			PluralName:     "cauliflowers",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "tomato",
			PluralName:     "tomatoes",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "bell pepper",
			PluralName:     "bell peppers",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "bok choy",
			PluralName:     "bok choys",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "leek",
			PluralName:     "leeks",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "brussel sprout",
			PluralName:     "brussel sprouts",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "green bean",
			PluralName:     "green beans",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "black bean",
			PluralName:     "black beans",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "pinto bean",
			PluralName:     "pinto beans",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "lima bean",
			PluralName:     "lima beans",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "kidney bean",
			PluralName:     "kidney beans",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "corn",
			PluralName:     "corns",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "jalapeno",
			PluralName:     "jalapenos",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "habanero",
			PluralName:     "habaneros",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "serrano",
			PluralName:     "serranos",
			HasWood:        false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsTree:         false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
	}

	return vegetables
}
