package organization

var (
	sizeClasses = []string{
		"small",
		"medium",
		"big",
	}

	sizeClassData = map[string]SizeClass{
		"small": {
			"small",
			6,
			20,
		},
		"medium": {
			"medium",
			21,
			50,
		},
		"big": {
			"big",
			51,
			100,
		},
	}

	types = []string{
		"adventuring company",
		"church",
		"guild",
		"mercenary company",
	}

	typeData = map[string]OrganizationType{
		"adventuring company": {
			"an adventuring company",
			[]string{
				"aggressive",
				"avaricious",
				"charismatic",
				"curious",
				"forceful",
				"heroic",
				"honorable",
				"reckless",
				"reserved",
				"selfless",
			},
			false,
			"captain",
			[]string{
				"Black",
				"Burning",
				"Crimson",
				"Free",
				"Righteous",
				"Silver",
				"Wandering",
				"White",
			},
			[]string{
				"Axes",
				"Blade",
				"Coin",
				"Company",
				"Dragons",
				"Giants",
				"Lords",
				"Pike",
				"Swords",
				"Wolves",
				"Wyverns",
			},
			"{{.FirstPart}} {{.SecondPart}}",
		},
		"church": {
			"a church",
			[]string{
				"penitent",
				"helpful",
				"selfless",
				"controlling",
				"merciful",
				"merciless",
				"penniless",
				"proselytizing",
			},
			true,
			"high priest",
			[]string{
				"Holy",
				"Glorious",
				"Exalted",
				"Humble",
				"Penitent",
				"Righteous",
			},
			[]string{
				"Divine Hand",
				"Dove",
				"Eye",
				"Flame",
				"Forest",
				"Four Truths",
				"Iron Path",
				"Light",
				"Meek",
				"Path",
				"River",
				"Sword",
				"Three Truths",
				"Truth",
			},
			"{{.FirstPart}} Church of the {{.SecondPart}}",
		},
		"guild": {
			"a guild",
			[]string{
				"ambitious",
				"avaricious",
				"charitable",
				"fair",
				"frugal",
				"lazy",
				"manipulative",
				"observant",
				"productive",
			},
			true,
			"guild leader",
			[]string{
				"August",
				"East Wind",
				"Global",
				"Imperial",
				"Incorporated",
				"North Wind",
				"Royal",
				"South Wind",
				"West Wind",
			},
			[]string{
				"Alchemist",
				"Apothecary",
				"Artist",
				"Blacksmith",
				"Bowyer",
				"Carpenter",
				"Fletcher",
				"Furrier",
				"Mason",
				"Merchant",
				"Moneylender",
				"Painter",
				"Sculptor",
				"Tanner",
			},
			"{{.FirstPart}} {{.SecondPart}}'s Guild",
		},
		"mercenary company": {
			"a mercenary company",
			[]string{
				"aggressive",
				"belligerent",
				"avaricious",
				"neutral",
				"honorable",
				"dishonorable",
				"trustworthy",
			},
			true,
			"captain",
			[]string{
				"Black",
				"Burning",
				"Crimson",
				"Free",
				"Gilded",
				"Ivory",
				"Silver",
				"White",
			},
			[]string{
				"Army",
				"Axes",
				"Company",
				"Dragons",
				"Giants",
				"Legion",
				"Lords",
				"Sentinels",
				"Swords",
				"Wolves",
				"Wyverns",
			},
			"{{.FirstPart}} {{.SecondPart}}",
		},
	}
)
