package plant

func getVegetables() []Plant {
	vegetables := []Plant{
		Plant{
			Name:           "potato",
			PluralName:     "potatoes",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         true,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "onion",
			PluralName:     "onions",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         true,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "beet",
			PluralName:     "beets",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         true,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "radish",
			PluralName:     "radishes",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         true,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "yam",
			PluralName:     "yams",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         true,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "carrot",
			PluralName:     "carrots",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         true,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "eggplant",
			PluralName:     "eggplants",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "kohlrabi",
			PluralName:     "kohlrabis",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "cabbage",
			PluralName:     "cabbages",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "lettuce",
			PluralName:     "lettuces",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "fiddlehead",
			PluralName:     "fiddleheads",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "broccoli",
			PluralName:     "broccolis",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "cauliflower",
			PluralName:     "cauliflowers",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "tomato",
			PluralName:     "tomatoes",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "bell pepper",
			PluralName:     "bell peppers",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "bok choy",
			PluralName:     "bok choys",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "leek",
			PluralName:     "leeks",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "brussel sprout",
			PluralName:     "brussel sprouts",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "green bean",
			PluralName:     "green beans",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "black bean",
			PluralName:     "black beans",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "pinto bean",
			PluralName:     "pinto beans",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "lima bean",
			PluralName:     "lima beans",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "kidney bean",
			PluralName:     "kidney beans",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "corn",
			PluralName:     "corns",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "jalapeno",
			PluralName:     "jalapenos",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "habanero",
			PluralName:     "habaneros",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
		Plant{
			Name:           "serrano",
			PluralName:     "serranos",
			IsFabric:       false,
			IsFiber:        false,
			IsFruit:        false,
			IsGrain:        false,
			IsHerb:         false,
			IsMedicine:     false,
			IsNut:          false,
			IsRoot:         false,
			IsSpice:        false,
			IsToxic:        false,
			IsVegetable:    true,
			MinHumidity:    3,
			MaxHumidity:    10,
			MinTemperature: 2,
			MaxTemperature: 10,
		},
	}

	return vegetables
}
